"""Build a proper-noun gazetteer from Macedonian Wikipedia link titles.

Titles that Macedonian articles link to are overwhelmingly people, places and
works — exactly the open class the frozen wordlist lacks. Only ns-0 titles
in Macedonian Cyrillic that are missing from every current lexicon input are
kept, so the file stays a curated category, not corpus-chased individuals.

Usage: python tools/build_gazetteer.py  (writes data/supplement/mk_names.txt)
"""
import json
import os
import re
import urllib.request
import urllib.parse

API = "https://mk.wikipedia.org/w/api.php"
UA = {"User-Agent": "macedonian-text/0.1 (local gazetteer)"}
# Hub articles whose outgoing links are dense with Macedonian names.
HUBS = ["Македонија", "Скопје", "Историја на Македонија",
        "Список на градови во Македонија", "Македонска книжевност"]
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Optional offline sources (one item per line, free downloads, not in repo):
# - mkwiki-latest-all-titles-in-ns0.gz -> data/raw/mkwiki-titles.txt
#   https://dumps.wikimedia.org/mkwiki/latest/mkwiki-latest-all-titles-in-ns0.gz
# - GeoNames MK.zip -> data/raw/mk_geonames.txt
#   https://download.geonames.org/export/zip/MK.zip
DUMP_TITLES = os.path.join(ROOT, "data", "raw", "mkwiki-titles.txt")
GEONAMES = os.path.join(ROOT, "data", "raw", "mk_geonames.txt")
OUT = os.path.join(ROOT, "data", "supplement", "mk_names.txt")
CYR = re.compile(r"^[Ѐ-Џа-шѓќѕџјљњќѓѐѝ]{3,30}$")


def api(params):
    q = urllib.parse.urlencode(params)
    req = urllib.request.Request(API + "?" + q, headers=UA)
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.load(r)


def links(title):
    out, cont = [], {}
    while True:
        d = api({"action": "query", "prop": "links", "titles": title,
                 "plnamespace": 0, "pllimit": 500, "format": "json",
                 "formatversion": 2, **cont})
        page = d["query"]["pages"][0]
        out += [l["title"] for l in page.get("links", [])]
        if "continue" not in d:
            return out
        cont = d["continue"]


def current_words():
    have = set()
    for name in ("mk_wordlist.utf8.txt",):
        p = os.path.join(ROOT, "data", "interim", name)
        with open(p, encoding="utf-8") as fh:
            have.update(l.strip().lower() for l in fh if l.strip() and not l.startswith("#"))
    for name in ("mk_supplement.txt", "mk_names.txt"):
        p = os.path.join(ROOT, "data", "supplement", name)
        if os.path.exists(p):
            with open(p, encoding="utf-8") as fh:
                have.update(l.strip().lower() for l in fh if l.strip() and not l.startswith("#"))
    p = os.path.join(ROOT, "data", "interim", "mk_apertium_forms.txt")
    if os.path.exists(p):
        with open(p, encoding="utf-8") as fh:
            have.update(l.strip().lower() for l in fh if l.strip())
    return have


def main():
    have = current_words()
    seen, kept = set(), []

    def consider(w):
        w = w.strip("«»\"'.,:;!?()")
        if not w or w.lower() in have or w.lower() in seen:
            return
        seen.add(w.lower())
        if CYR.match(w) and not w.isupper():
            kept.append(w)

    for hub in HUBS:
        for title in links(hub):
            for part in title.split():
                consider(part)
    # Offline dumps use the identical filter, so results stay comparable.
    for path in (DUMP_TITLES, GEONAMES):
        if os.path.exists(path):
            with open(path, encoding="utf-8") as fh:
                for line in fh:
                    line = line.strip()
                    if not line or line.startswith("#"):
                        continue
                    for part in line.split():
                        consider(part)
    kept = sorted(set(kept))
    # Never shrink the curated file: a crawl that finds nothing (changed hub
    # contents, API hiccup) must fail loudly instead of wiping reviewed names.
    existing = 0
    if os.path.exists(OUT):
        with open(OUT, encoding="utf-8") as fh:
            existing = sum(1 for l in fh if l.strip() and not l.startswith("#"))
    if len(kept) < existing:
        print(f"GAZETTEER-REFUSED kept={len(kept)} existing={existing}: crawl found less, file untouched")
        raise SystemExit(1)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("# Proper-noun gazetteer: Macedonian Wikipedia link titles\n")
        fh.write("# (people, places, works) absent from the wordlist and paradigms.\n")
        fh.write("# Generated by tools/build_gazetteer.py; review diffs before committing.\n")
        fh.write("\n".join(kept) + "\n")
    print(f"hubs={len(HUBS)} candidates={len(seen)} kept={len(kept)}")


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print("GAZETTEER-FAILED " + ascii(str(e))[:200])
        raise SystemExit(1)
